# Generated by Django 4.1 on 2024-06-01 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Todo", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="datecompleted",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
